name: Bug Report
description: Tell up about a bug that you spotted
labels: ["bug", "triage"]
body:
- type: dropdown
  id: importance
  attributes:
    label: How important is this bug?
    options:
      - Slightly Annoying
      - Annoying
      - Game-breaking
      - Crash
  validations:
    required: true
- type: textarea
  id: repro
  attributes:
    label: Reproduction steps
    description: "How do you trigger this bug? Please walk us through it step by step."
    value: |
      1.
      2.
      3.
      ...
    render: bash
  validations:
    required: true
- type: textarea
  id: logs
  attributes:
    label: Relevant log output
    description: Please copy and paste any relevant log output.
    render: shell
- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to follow our [Code of Conduct](). 
    options:
      - label: I agree to follow this project's Code of Conduct
        required: true
