name: Feature Request
description: A request for a new feature
body:
  - type: dropdown
    id: area
    attributes:
      label: Part
      description: Which part of RPyG would this feature improve?
      multiple: true
      options:
        - Gameplay
        - Framework
        - Performance
        - Other (Please Specify)
    validations:
      required: true
  - type: input
    id: other
    attributes:
      label: Part (if you chose other)
      description: If you chose other for the previous answer, type the part of the game that it would affect
      
  - type: textarea
    id: feature
    attributes:
      label: Description
      description: A description of the feature you want to see implemented
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
